import json, pathlib
D = pathlib.Path('data')
lc = json.load(open(D/'lightcast.json')); sow = json.load(open(D/'sow.json'))
cps = json.load(open(D/'cps.json')); ppl = json.load(open(D/'people.json'))
pct = json.load(open(D/'percentiles.json'))
print("families[0]  :", {k: lc['families'][0][k] for k in list(lc['families'][0])[:9]})
print("tiers[0]     :", lc['tiers'][0])
print("sizeTiers[0] :", {k: lc['sizeTiers'][0][k] for k in list(lc['sizeTiers'][0])[:7]})
print("topOcc[0]    :", {k: lc['topOcc'][0][k] for k in ('soc','n','j','m')})
print("eduDetail[0] :", lc['eduDetail'][0])
print("opp.top[0]   :", {k: sow['opp']['top'][0][k] for k in ('n','sc','t','j')})
print("vscs.byFamily[0]:", sow['vscs']['byFamily'][0])
print("regions[0]   :", sow['regions'][0])
print("cps.trend[-1]:", cps['trend'][-1])
print("famTrend[0]  :", cps['famTrend'][0] if 'famTrend' in cps else 'n/a')
print("byCred[0]    :", {k: ppl['byCred'][0][k] for k in ('label','n','avg','med')})
print("pct.tiers k  :", list(pct['tiers']['High school'].keys()))
